name: Elixir CI
on: 
  push
jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sets up an Erlang/OTP environment
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.13.1'
          otp-version: '24.2'

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: exacto-knife-${{ runner.os }}-mix-1.13.1-${{ hashFiles('mix.lock') }}

      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix deps.get
          mix deps.unlock --check-unused
          mix deps.compile

      - name: Compile
        run: |
          mix compile

      - name: Credo
        run: |
          mix credo --strict

      - name: Format
        run: |
          mix format --check-formatted

      - name: Run Tests
        run: |
          mix test
